# Generated by Django 3.0.2 on 2020-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideomodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_videos'),
        ),
        migrations.AlterField(
            model_name='uploadvideomodel',
            name='video_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadvideomodel',
            name='video_tags',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='uploadvideomodel',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
