# Generated by Django 3.0.2 on 2020-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_auto_20200812_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideomodel',
            name='user_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideomodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideomodel',
            name='user_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideomodel',
            name='user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
