# Generated by Django 3.0.2 on 2020-08-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_auto_20200816_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideomodel',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='uploadvideomodel',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='uploadvideomodel',
            name='user_profile_pic',
        ),
    ]
